import Head from "next/head";

import NavBar from "@/components/NavBar";
import Container from "@/components/Container";
import Hero from "@/components/Hero";
import Projects from "@/components/Projects";
import Footer from "@/components/Footer";
import About from "@/components/About";
import Contact from "@/components/Contact";
import Map from "@/components/Map";

export default function Home() {
  return (
    <>
      <Head>
        <title>Architects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar></NavBar>
        <Hero></Hero>
        <Container>
          <Projects></Projects>
          <About></About>
          <Contact></Contact>
          <Map></Map>
        </Container>
        <Footer></Footer>
      </main>
    </>
  );
}
